//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseMngr
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnLoad
    {
        public string LoadID { get; set; }
        public string LoadArticle { get; set; }
        public string LoadName { get; set; }
        public System.DateTime LoadDate { get; set; }
        public int Loader { get; set; }
        public decimal LoadPrice { get; set; }
        public int LoadCount { get; set; }
        public short LoadType { get; set; }
    
        public virtual Clents Clents { get; set; }
        public virtual Type Type { get; set; }
    }
}
