//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseMngr
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserLName { get; set; }
        public string UserFName { get; set; }
        public string UserLogin { get; set; }
        public string UserPass { get; set; }
        public short UserRole { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
