//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseMngr
{
    using System;
    using System.Collections.Generic;
    
    public partial class WHProds
    {
        public int ProdID { get; set; }
        public string ProdArticle { get; set; }
        public string ProdName { get; set; }
        public string ProdLoc { get; set; }
        public decimal ProdPrice { get; set; }
        public int ProdCount { get; set; }
        public short ProdType { get; set; }
        public System.DateTime ProdDate { get; set; }
        public byte[] ProdImg { get; set; }
    
        public virtual Type Type { get; set; }
    }
}
